### PR TITLE
fixes #80

### LINKED ISSUE #80: FakeTransaction causes hash collisions in ganache-cli
Ganache/TestRPC experiences transaction hash collisions when the only thing differentiating two transactions is the sender, for example, when two brand new accounts send identical transactions to the same contract.

Example:

I'd expect that in the below code, `tx1.hash()` would not be the same as `tx2.hash()`.

```javascript
    var tx1 = new FakeTransaction({
        data:"0x7cf5dab00000000000000000000000000000000000000000000000000000000000000005",
        gasLimit:"0x15f90",
        gasPrice:"0x1",
        nonce:"0x01",
        to:"0xd9024df085d09398ec76fbed18cac0e1149f50dc",
        value:"0x0",
        from: "0xf492dd75de5acfe13ef9bae89a0f51767be3dae5"
    });

    var tx2 = new FakeTransaction({
        data:"0x7cf5dab00000000000000000000000000000000000000000000000000000000000000005",
        gasLimit:"0x15f90",
        gasPrice:"0x1",
        nonce:"0x01",
        to:"0xd9024df085d09398ec76fbed18cac0e1149f50dc",
        value:"0x0",
        from: "0x161b4555e40f6d42ae93591f3d9f35f6e765c6b9"
    });

    // fails
    assert.notEqual(tx1.hash(), tx2.hash());
```

### PR DESCRIPTION
**Pull request by benjamincburns**
Fixes #80 - Don't produce hash collisions on FakeTransaction for different senders

### CODE REVIEW

File: fake.js [hunk 1]
```diff
@@ -53,4 +53,38 @@ module.exports = class FakeTransaction extends Transaction {
...
+
+    // EIP155 spec:
+    // when computing the hash of a transaction for purposes of signing or recovering,
+    // instead of hashing only the first six elements (ie. nonce, gasprice, startgas, to, value, data),
+    // hash nine elements, with v replaced by CHAIN_ID, r = 0 and s = 0
+
+    let items
+    if (includeSignature) {
+      items = this.raw
+      items += this.getSenderAddress();
```
Comment (axic) [inline fake.js]: I think instead of duplicating, `fakeTransaction` should change `.raw` in the constructor to include the signature (a fake one perhaps). The `hash` method then is inherited unchanged from the normal implementation.

This is a lot of code duplication otherwise.

Comment (benjamincburns) [reply fake.js]: @axic I think I can accommodate that easily enough. However, does that mean that instead of overriding `hash` we'll need to override `sign`?

Comment (benjamincburns) [reply fake.js]: Also thanks for the fast response!

Comment (benjamincburns) [reply fake.js]: @axic see latest changes. I'm not sure that I like this however, as I feel `sign` should probably be overridden as well to avoid cases where the fake signature is overwritten.

**Comment by benjamincburns** [comment]
@jwasinger well that's embarrassing! Pushing the fix now.

**Comment by benjamincburns** [comment]
And a half hour later I've found the right mixture of whitespace to avoid offending `standard` 😒

**Comment by jwasinger** [comment]
lol isn't that always fun :D can you squash some of the commits to clean up the history? then I will merge.

**Comment by benjamincburns** [comment]
squashed.

**Comment by benjamincburns** [comment]
Thanks, @jwasinger!

**Comment by kumavis** [comment]
@benjamincburns protip: `standard --fix`

**Comment by benjamincburns** [comment]
Thanks, @kumavis - maybe I have a shitty old version installed, but it never seems to do anything for me...
